In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('df1.csv',  encoding='UTF-8')

In [3]:
df.head()

   id                                               text  label
0   1  всем холодный душ из водомётов и не одного евр...    1.0
1   2                              я поляк я люблю тебе     0.0
2   3              автор хуй из рта вытащи беркут герои     1.0
3   4  позор януковичу не замочил майданщиков продажн...    1.0
4   5                       легче всего обвинять россию     0.0

In [4]:
df.isna().sum()

id       0
text     0
label    0
dtype: int64

In [5]:
df.head()

   id                                               text  label
0   1  всем холодный душ из водомётов и не одного евр...    1.0
1   2                              я поляк я люблю тебе     0.0
2   3              автор хуй из рта вытащи беркут герои     1.0
3   4  позор януковичу не замочил майданщиков продажн...    1.0
4   5                       легче всего обвинять россию     0.0

In [6]:
df.tail()

        id                                               text  label
1995  1996  вот из за таких гоблинов пропукинских и погиба...    1.0
1996  1997     беркут наведите порядок конце концов в стране     0.0
1997  1998        слава україні героям слава смерть москалям     1.0
1998  1999  под бла бла бла таких хакамад мы и потеряли сс...    1.0
1999  2000  на рахунок олігархів згідний але їх що на росі...    0.0

In [7]:
df['text'].unique

<bound method Series.unique of 0       всем холодный душ из водомётов и не одного евр...
1                                   я поляк я люблю тебе
2                   автор хуй из рта вытащи беркут герои
3       позор януковичу не замочил майданщиков продажн...
4                            легче всего обвинять россию
                              ...
1995    вот из за таких гоблинов пропукинских и погиба...
1996       беркут наведите порядок конце концов в стране
1997          слава україні героям слава смерть москалям
1998    под бла бла бла таких хакамад мы и потеряли сс...
1999    на рахунок олігархів згідний але їх що на росі...
Name: text, Length: 2000, dtype: object>

In [8]:
import string

In [9]:
df.head()

   id                                               text  label
0   1  всем холодный душ из водомётов и не одного евр...    1.0
1   2                              я поляк я люблю тебе     0.0
2   3              автор хуй из рта вытащи беркут герои     1.0
3   4  позор януковичу не замочил майданщиков продажн...    1.0
4   5                       легче всего обвинять россию     0.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      2000 non-null   int64
 1   text    2000 non-null   object
 2   label   2000 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 47.0+ KB

In [11]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [12]:
print(stopwords.words('russian'))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

In [13]:
print(df['text'].apply(type).value_counts())

<class 'str'>    2000
Name: text, dtype: int64

In [14]:
!pip install stop-words

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting stop-words
  Downloading stop-words-2018.7.23.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: stop-words
  Building wheel for stop-words (setup.py) ... done
  Created wheel for stop-words: filename=stop_words-2018.7.23-py3-none-any.whl size=32910 sha256=ccc8aa5e9ccde7af2d2a9f8e4f9b7283e151bb9bd75216d256d9875796e6c961
  Stored in directory: /root/.cache/pip/wheels/da/d8/66/395317506a23a9d1d7de433ad6a7d9e6e16aab48cf028a0f60
Successfully built stop-words
Installing collected packages: stop-words
Successfully installed stop-words-2018.7.23

In [15]:
import stop_words
#stop_words_russian = set(stopwords.words('russian'))
stop_words_russian = stop_words.get_stop_words('russian')

In [16]:
# Convert non-string values to empty string
df['text'] = df['text'].apply(lambda x: str(x) if type(x) != str else x)

# Remove stop words from the text column
df['text'] = df['text'].apply(lambda x: ' '.join([word for word in x.split() if word.lower() not in stop_words_russian]))

In [17]:
df.head()

   id                                               text  label
0   1     холодный душ водомётов европидо ста останеться    1.0
1   2                                        поляк люблю    0.0
2   3                  автор хуй рта вытащи беркут герои    1.0
3   4  позор януковичу замочил майданщиков продажная ...    1.0
4   5                              легче обвинять россию    0.0

In [18]:
# Define a function to convert text to lowercase
def convert_to_lower(text):
    return text.lower()

# Apply the function to the 'text' column of the DataFrame
df['text'] = df['text'].apply(convert_to_lower)

In [19]:
df.head(15)

    id                                               text  label
0    1     холодный душ водомётов европидо ста останеться    1.0
1    2                                        поляк люблю    0.0
2    3                  автор хуй рта вытащи беркут герои    1.0
3    4  позор януковичу замочил майданщиков продажная ...    1.0
4    5                              легче обвинять россию    0.0
5    6                  росия говно україна країна героїв    1.0
6    7                         эх танком круче смотрелось    0.0
7    8                                як можна брат брата    0.0
8    9                              владимир владимирович    0.0
9   10    сука продажная платят бред тварь слушают терпят    1.0
10  11                                    спишь сша война    0.0
11  12  ребята прислушаемся словам янушеску вставай ук...    1.0
12  13                        народ друг друга ненавидите    0.0
13  14  роман сыроватко страна стремительно деградируе...    1.0
14  15    сеера макс живу восточной украине самая задница    1.0

In [20]:
import re
def remove_urls(text):
    return re.sub(r'http\S+', '', text)
# Apply the function to the 'text' column of the DataFrame
df['text'] = df['text'].apply(remove_urls)

In [21]:
df.tail(20)

        id                                               text  label
1980  1981  виталий журба секции политпросвещения обкомах ...    0.0
1981  1982  какие защитники мать вашу омону беркуту первым...    0.0
1982  1983  хлопци хотят стерпим хуже будущее белорусии хо...    0.0
1983  1984                                       героям слива    0.0
1984  1985   грубо пустой звук последний крик умирающего быка    0.0
1985  1986  макс курбатов януковича шибко никто поддержива...    0.0
1986  1987  улирих жуков закончили российской культурой не...    0.0
1987  1988  любовь шнырева личности переходил свой уровень...    1.0
1988  1989                  дай бог здоровья парниша души пел    0.0
1989  1990  информаторы единой федерации гнилопяткинские ж...    1.0
1990  1991  янукович ужасный котором доллар порошенко раза...    0.0
1991  1992                                    свободы хватает    0.0
1992  1993  татаро монгольское иго угнетало погибших разру...    0.0
1993  1994                        развели пидорятник виноваты    1.0
1994  1995  старая жена путина вряд родит молодая гимнастк...    0.0
1995  1996  таких гоблинов пропукинских погибают всякая мр...    1.0
1996  1997        беркут наведите порядок конце концов стране    0.0
1997  1998         слава україні героям слава смерть москалям    1.0
1998  1999  бла бла бла таких хакамад потеряли ссср мерзка...    1.0
1999  2000  рахунок олігархів згідний але їх що росії вже ...    0.0

In [22]:
# Define a function to remove punctuation and extra spaces from a text string
def remove_punct_and_extra_space(text):
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove extra space
    text = re.sub(' +', ' ', text)
    return text

# Apply the function to the 'text' column of the DataFrame
df['text'] = df['text'].apply(remove_punct_and_extra_space)

In [23]:
df.tail(15)

        id                                               text  label
1985  1986  макс курбатов януковича шибко никто поддержива...    0.0
1986  1987  улирих жуков закончили российской культурой не...    0.0
1987  1988  любовь шнырева личности переходил свой уровень...    1.0
1988  1989                  дай бог здоровья парниша души пел    0.0
1989  1990  информаторы единой федерации гнилопяткинские ж...    1.0
1990  1991  янукович ужасный котором доллар порошенко раза...    0.0
1991  1992                                    свободы хватает    0.0
1992  1993  татаро монгольское иго угнетало погибших разру...    0.0
1993  1994                        развели пидорятник виноваты    1.0
1994  1995  старая жена путина вряд родит молодая гимнастк...    0.0
1995  1996  таких гоблинов пропукинских погибают всякая мр...    1.0
1996  1997        беркут наведите порядок конце концов стране    0.0
1997  1998         слава україні героям слава смерть москалям    1.0
1998  1999  бла бла бла таких хакамад потеряли ссср мерзка...    1.0
1999  2000  рахунок олігархів згідний але їх що росії вже ...    0.0

In [24]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Unzipping help/tagsets.zip.

True

In [25]:
# Tokenize the text in the 'text' column
df['text_tokenized'] = df['text'].apply(lambda x: nltk.word_tokenize(x))

In [26]:
df.tail(15)

,id,text,label,text_tokenized
1985,1986,макс курбатов януковича шибко никто поддержива...,0.0,"[макс, курбатов, януковича, шибко, никто, подд..."
1986,1987,улирих жуков закончили российской культурой не...,0.0,"[улирих, жуков, закончили, российской, культур..."
1987,1988,любовь шнырева личности переходил свой уровень...,1.0,"[любовь, шнырева, личности, переходил, свой, у..."
1988,1989,дай бог здоровья парниша души пел,0.0,"[дай, бог, здоровья, парниша, души, пел]"
1989,1990,информаторы единой федерации гнилопяткинские ж...,1.0,"[информаторы, единой, федерации, гнилопяткинск..."
1990,1991,янукович ужасный котором доллар порошенко раза...,0.0,"[янукович, ужасный, котором, доллар, порошенко..."
1991,1992,свободы хватает,0.0,"[свободы, хватает]"
1992,1993,татаро монгольское иго угнетало погибших разру...,0.0,"[татаро, монгольское, иго, угнетало, погибших,..."
1993,1994,развели пидорятник виноваты,1.0,"[развели, пидорятник, виноваты]"
1994,1995,старая жена путина вряд родит молодая гимнастк...,0.0,"[старая, жена, путина, вряд, родит, молодая, г..."
1995,1996,таких гоблинов пропукинских погибают всякая мр...,1.0,"[таких, гоблинов, пропукинских, погибают, всяк..."
1996,1997,беркут наведите порядок конце концов стране,0.0,"[беркут, наведите, порядок, конце, концов, стр..."
1997,1998,слава україні героям слава смерть москалям,1.0,"[слава, україні, героям, слава, смерть, москалям]"
1998,1999,бла бла бла таких хакамад потеряли ссср мерзка...,1.0,"[бла, бла, бла, таких, хакамад, потеряли, ссср..."
1999,2000,рахунок олігархів згідний але їх що росії вже ...,0.0,"[рахунок, олігархів, згідний, але, їх, що, рос..."

In [27]:
!pip install pymorphy2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pymorphy2
  Downloading pymorphy2-0.9.1-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 KB 5.7 MB/s eta 0:00:00
Collecting dawg-python>=0.7.1
  Downloading DAWG_Python-0.7.2-py2.py3-none-any.whl (11 kB)
Collecting pymorphy2-dicts-ru<3.0,>=2.4
  Downloading pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 79.9 MB/s eta 0:00:00
Collecting docopt>=0.6
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13721 sha256=7f1f78e3f4b37fa2e118f587e469f5638cdc0d4ce19005ee8a6db5ee84f45f62
  Stored in directory: /root/.cache/pip/wheels/70/4a/46/1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
Successfully built docopt
Installing collected packages: pymorphy2-dicts-ru, docopt, dawg-python, pymorphy2
Successfully installed dawg-python-0.7.2 docopt-0.6.2 pymorphy2-0.9.1 pymorphy2-dicts-ru-2.4.417127.4579844

In [28]:
import re
from pymorphy2 import MorphAnalyzer
from nltk.corpus import stopwords

patterns = "[A-Za-z0-9!#$%&'()*+,./:;<=>?@[\]^_`{|}~—\"\-]+"
stopwords_ru = stopwords.words("russian")
morph = MorphAnalyzer()

def lemmatize(doc):
    doc = re.sub(patterns, ' ', doc)
    tokens = []
    for token in doc.split():
        if token and token not in stopwords_ru:
            token = token.strip()
            token = morph.normal_forms(token)[0]
            
            tokens.append(token)
    if len(tokens) >= 1:
        return tokens
    return None

data = df.text.apply(lemmatize)
#data = data.dropna()
data

0       [холодный, душа, водомёт, европидо, сто, остан...
1                                         [поляк, любить]
2              [автор, хуй, рот, вытащить, беркут, герой]
3       [позор, янукович, замочить, майданщик, продажн...
4                              [лёгкий, обвинять, россия]
                              ...
1995    [такой, гоблин, пропукинский, погибать, всякий...
1996     [беркут, навести, порядок, конец, конец, страна]
1997      [слава, україні, герой, слава, смерть, москаль]
1998    [бла, бла, бла, такой, хакамада, потерять, ссс...
1999    [рахунок, олігархіть, згідний, але, їх, що, ро...
Name: text, Length: 2000, dtype: object

In [29]:
df3=pd.DataFrame(columns=['id','text','label'])
df3['text']=data
df3['id']=df['id']
df3['label']=df['label']
df3=df3.dropna()
df3

        id                                               text  label
0        1  [холодный, душа, водомёт, европидо, сто, остан...    1.0
1        2                                    [поляк, любить]    0.0
2        3         [автор, хуй, рот, вытащить, беркут, герой]    1.0
3        4  [позор, янукович, замочить, майданщик, продажн...    1.0
4        5                         [лёгкий, обвинять, россия]    0.0
...    ...                                                ...    ...
1995  1996  [такой, гоблин, пропукинский, погибать, всякий...    1.0
1996  1997   [беркут, навести, порядок, конец, конец, страна]    0.0
1997  1998    [слава, україні, герой, слава, смерть, москаль]    1.0
1998  1999  [бла, бла, бла, такой, хакамада, потерять, ссс...    1.0
1999  2000  [рахунок, олігархіть, згідний, але, їх, що, ро...    0.0

[1980 rows x 3 columns]

In [30]:
df3.isna().sum()

id       0
text     0
label    0
dtype: int64

In [31]:
df3.count()

id       1980
text     1980
label    1980
dtype: int64